language: go

sudo: required

go:
  - "1.11.2"
  - master

dist: trusty

addons:
  postgresql: "9.6.6"

services:
  - postgresql
  - redis-server

before_script:
  # restart redis
  - redis-cli shutdown
  - sudo redis-server --requirepass 'password' & echo "完成redis的启动"
  # restart postgres
  - sudo /etc/init.d/postgresql stop & sudo /etc/init.d/postgresql start
  # start postgres
  - psql -c 'create database gotest;' -U postgres

  - go get -t -v ./...

script: make test && make build