language: go

go:
  - "1.11.2"
  - master

addons:
  postgresql: "9.6.6"

services:
  - postgresql
  - redis-server

before_script:
  # showdown redis
  - redis-cli shutdown
  # start redis
  - sudo redis-server --requirepass 'password' & echo "完成redis的启动"
  # start postgres
  - psql -c 'create database gotest;' -U postgres

script:
  - make test
  - make build