language: go

sudo: required

go:
  - "1.11.2"
  - "1.12"

dist: trusty

addons:
  postgresql: "9.6.6"

env:
  global:
    - DB_DRIVER=postgres
    - DB_NAME=gotest
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DB_PORT=5432

services:
  - postgresql
  - redis-server

before_script:
  # restart redis
  - redis-cli shutdown
  - sudo redis-server --requirepass 'password' & echo "完成redis的启动"
  # restart postgres
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start
  # start postgres
  - psql -c 'create database gotest;' -U postgres

  - go get -t -v ./...

script:
  - make test
  - make build

after_success:
  # report code cover
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN