version: '3'
services:
  # 数据库
  pg:
    image: postgres:9.6.6-alpine
    restart: always
    volumes:
      - "./docker/volumes/pg:/var/lib/postgresql/data"
    ports:
      - 65432:5432
  # 缓存
  redis:
    image: redis:5.0.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "./docker/volumes/redis:/data"
    environment:
      - REDIS_PASSWORD=password
    command: [ "redis-server", "--requirepass", "password" ]